export const GET_FAILURE_CAUSES_SUCCESS = "GET_FAILURE_CAUSES_SUCCESS";
export const ADD_FAILURE_CAUSE_SUCCESS = "ADD_FAILURE_CAUSE_SUCCESS";
export const UPDATE_FAILURE_CAUSE_SUCCESS = "UPDATE_FAILURE_CAUSE_SUCCESS";
export const DELETE_FAILURE_CAUSE_SUCCESS = "DELETE_FAILURE_CAUSE_SUCCESS";
export const SET_SELECTED_FAILURE_CAUSE = "SET_SELECTED_FAILURE_CAUSE";
