export const GET_FAILURE_EFFECTS_SUCCESS = "GET_FAILURE_EFFECTS_SUCCESS";
export const ADD_FAILURE_EFFECT_SUCCESS = "ADD_FAILURE_EFFECT_SUCCESS";
export const UPDATE_FAILURE_EFFECT_SUCCESS = "UPDATE_FAILURE_EFFECT_SUCCESS";
export const DELETE_FAILURE_EFFECT_SUCCESS = "DELETE_FAILURE_EFFECT_SUCCESS";
export const SET_SELECTED_FAILURE_EFFECT = "SET_SELECTED_FAILURE_EFFECT";
