export const GET_FAILURE_MODES_SUCCESS = "GET_FAILURE_MODES_SUCCESS";
export const ADD_FAILURE_MODE_SUCCESS = "ADD_FAILURE_MODE_SUCCESS";
export const UPDATE_FAILURE_MODE_SUCCESS = "UPDATE_FAILURE_MODE_SUCCESS";
export const DELETE_FAILURE_MODE_SUCCESS = "DELETE_FAILURE_MODE_SUCCESS";
export const SET_SELECTED_FAILURE_MODE = "SET_SELECTED_FAILURE_MODE";
