export const GET_FUNCTIONS_SUCCESS = "GET_FUNCTIONS_SUCCESS";
export const ADD_FUNCTION_SUCCESS = "ADD_FUNCTION_SUCCESS";
export const GET_SUB_FUNCTIONS_SUCCESS = "GET_SUB_FUNCTIONS_SUCCESS";
export const ADD_SUB_FUNCTIONS_SUCCESS = "ADD_SUB_FUNCTIONS_SUCCESS";
