export const GET_FUNCTIONS_SUCCESS = "GET_FUNCTIONS_SUCCESS";
export const ADD_FUNCTION_SUCCESS = "ADD_FUNCTION_SUCCESS";
export const UPDATE_FUNCTION_SUCCESS = "UPDATE_FUNCTION_SUCCESS";
export const DELETE_FUNCTION_SUCCESS = "DELETE_FUNCTION_SUCCESS";
export const SET_SELECTED_FUNCTION = "SET_SELECTED_FUNCTION";
