export const GET_INPUTS_SUCCESS = "GET_INPUTS_SUCCESS";
export const ADD_INPUT_SUCCESS = "ADD_INPUT_SUCCESS";
export const UPDATE_INPUT_SUCCESS = "UPDATE_INPUT_SUCCESS";
export const DELETE_INPUT_SUCCESS = "DELETE_INPUT_SUCCESS";
export const SET_SELECTED_INPUT = "SET_SELECTED_INPUT";
