export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const SET_SELECTED_NODE = "SET_SELECTED_NODE";
export const SET_FUNCTION_DATA = "SET_FUNCTION_DATA";
