export const GET_NOISE_FACTORS_SUCCESS = "GET_NOISE_FACTORS_SUCCESS";
export const ADD_NOISE_FACTOR_SUCCESS = "ADD_NOISE_FACTOR_SUCCESS";
export const UPDATE_NOISE_FACTOR_SUCCESS = "UPDATE_NOISE_FACTOR_SUCCESS";
export const DELETE_NOISE_FACTOR_SUCCESS = "DELETE_NOISE_FACTOR_SUCCESS";
export const SET_SELECTED_NOISE_FACTOR = "SET_SELECTED_NOISE_FACTOR";
