export const GET_OUTPUTS_SUCCESS = "GET_OUTPUTS_SUCCESS";
export const ADD_OUTPUT_SUCCESS = "ADD_OUTPUT_SUCCESS";
export const UPDATE_OUTPUT_SUCCESS = "UPDATE_OUTPUT_SUCCESS";
export const DELETE_OUTPUT_SUCCESS = "DELETE_OUTPUT_SUCCESS";
export const SET_SELECTED_OUTPUT = "SET_SELECTED_OUTPUT";
