export const GET_PREVENTION_CONTROLS_SUCCESS =
  "GET_PREVENTION_CONTROLS_SUCCESS";
export const ADD_PREVENTION_CONTROL_SUCCESS = "ADD_PREVENTION_CONTROL_SUCCESS";
export const UPDATE_PREVENTION_CONTROL_SUCCESS =
  "UPDATE_PREVENTION_CONTROL_SUCCESS";
export const DELETE_PREVENTION_CONTROL_SUCCESS =
  "DELETE_PREVENTION_CONTROL_SUCCESS";
export const SET_SELECTED_PREVENTION_CONTROL =
  "SET_SELECTED_PREVENTION_CONTROL";
