export const GET_PROGRAMS_SUCCESS = "GET_PROGRAMS_SUCCESS";
export const ADD_PROGRAM_SUCCESS = "ADD_PROGRAM_SUCCESS";
export const UPDATE_PROGRAM_SUCCESS = "UPDATE_PROGRAM_SUCCESS";
export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const SET_SELECTED_PROGRAM = "SET_SELECTED_PROGRAM";
