export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const GET_SUB_PROJECTS_SUCCESS = "GET_SUB_PROJECTS_SUCCESS";
export const ADD_SUB_PROJECTS_SUCCESS = "ADD_SUB_PROJECTS_SUCCESS";
export const SET_PROJECT = "SET_PROJECT";
export const GET_INPUTS_SUCCESS = "GET_INPUTS_SUCCESS";
export const GET_OUTPUTS_SUCCESS = "GET_OUTPUTS_SUCCESS";
