export const GET_SAFETY_REQUIREMENTS_SUCCESS =
  "GET_SAFETY_REQUIREMENTS_SUCCESS";
export const ADD_SAFETY_REQUIREMENT_SUCCESS = "ADD_SAFETY_REQUIREMENT_SUCCESS";
export const UPDATE_SAFETY_REQUIREMENT_SUCCESS =
  "UPDATE_SAFETY_REQUIREMENT_SUCCESS";
export const DELETE_SAFETY_REQUIREMENT_SUCCESS =
  "DELETE_SAFETY_REQUIREMENT_SUCCESS";
export const SET_SELECTED_SAFETY_REQUIREMENT =
  "SET_SELECTED_SAFETY_REQUIREMENT";
